from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_experimental.text_splitter import SemanticChunker
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_core.documents import Document
from dotenv import load_dotenv

load_dotenv()

text = """
Artificial Intelligence (AI) is transforming the way humans interact with technology. From voice assistants to recommendation systems, AI is deeply embedded in our daily lives. Machine learning, a subset of AI, allows systems to learn patterns from data and make decisions without being explicitly programmed. Deep learning, a further specialization, uses neural networks with multiple layers to process complex data such as images, audio, and text.

Natural Language Processing (NLP) is another important branch of AI that focuses on enabling machines to understand and generate human language. Applications of NLP include chatbots, translation services, sentiment analysis, and text summarization. With the rise of large language models, machines are now capable of generating human-like text responses, making interactions more natural and efficient.

One of the key challenges in AI systems is handling large volumes of data effectively. Techniques like data preprocessing, tokenization, and text splitting help break down complex data into manageable chunks. Text splitting is especially useful in Retrieval-Augmented Generation (RAG) systems, where documents are divided into smaller pieces before being stored in a vector database.

Vector databases such as ChromaDB or FAISS are used to store embeddings of text chunks. These embeddings capture the semantic meaning of the text, allowing systems to retrieve relevant information based on similarity rather than exact keyword matches. This improves the quality and relevance of responses generated by AI models.

Despite its advantages, AI also comes with ethical concerns. Issues such as data privacy, bias in models, and transparency need to be addressed to ensure responsible AI development. Researchers and developers are actively working on making AI systems more fair, explainable, and secure.

The future of AI holds immense potential. With advancements in computing power and algorithms, AI systems are expected to become more intelligent, efficient, and capable of solving complex real-world problems. As AI continues to evolve, it will play a crucial role in shaping industries such as healthcare, finance, education, and transportation.
"""

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)
chunks = splitter.split_text(text=text)

print(len(chunks))
print(chunks)

#semantic_splitter = SemanticChunker(embeddings=GoogleGenerativeAIEmbeddings(model="gemini-embedding-2-preview"),
 #                                   breakpoint_threshold_type="percentile", breakpoint_threshold_amount=90)
#chunks = semantic_splitter.create_documents("Sentence one. Sentence two. Sentence three.")
#print(len(chunks))
#print(chunks)
